name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        logout: true

    - name: build image
      run: |
        docker build -t simplebank:latest .

        docker tag simplebank:latest ${{ secrets.USERNAME }}/simplebank:${{ github.sha }}
        docker push ${{ secrets.USERNAME }}/simplebank:${{ github.sha }}

    - name: Trigger CI
      uses: InformaticsMatters/trigger-ci-action@1.0.1
      with:
        ci-owner: pyfs
        ci-repository: flask-demo-kustomize
        ci-ref: refs/heads/master
        ci-user: pyfs
        ci-user-token: ${{ secrets.CI_TOKEN }}
        ci-name: CI
        ci-inputs: >-
          image=${{ secrets.USERNAME }}/flask-demo
          sha-tag=${{ github.sha }}



