name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: install migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate
  
    - name: migrate
      run: make migrateupgithub

    - name: Test
      run: make test

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        logout: true

    - name: build image
      run: |
        docker build -t ${{ secrets.USERNAME }}/simplebank:${{ github.sha }} -t ${{ secrets.USERNAME }}/simplebank:latest .
        docker push -a ${{ secrets.USERNAME }}/simplebank
      
    - name: Trigger CI
      uses: InformaticsMatters/trigger-ci-action@1.0.1
      with:
        ci-owner: csdengh
        ci-repository: simplebankCD
        ci-ref: refs/heads/main
        ci-user: csdengh
        ci-user-token: ${{ secrets.CI_TOKEN }}
        ci-name: CD
        ci-inputs: >-
          image=${{ secrets.USERNAME }}/simplebank
          sha-tag=${{ github.sha }}

  
  
